package com.revature.models;

public enum ThrowEnum {
	DYNAMITE, TORNADO, QUICKSAND, PIT, CHAIN, GUN, LAW, WHIP, SWORD, ROCK, DEATH, WALL, SUN, CAMERA, FIRE, CHAINSAW, SCHOOL, SCISSORS, POISON, CAGE, AXE, PEACE, COMPUTER, CASTLE, SNAKE, BLOOD, PORCUPINE, VULTURE, MONKEY, KING, QUEEN, PRINCE, PRINCESS, POLICE, WOMAN, BABY, MAN, HOME, TRAIN, CAR, NOISE, BICYCLE, TREE, TURNIP, DUCK, WOLF, CAT, BIRD, FISH, SPIDER, COCKROACH, BRAIN, CROSS, MONEY, VAMPIRE, SPONGE, CHURCH, BUTTER, BOOK, PAPER, CLOUD, AIRPLANE, MOON, GRASS, FILM, TOILET, AIR, PLANET, GUITAR, BOWL, CUP, BEER, RAIN, WATER, TV, RAINBOW, UFO, ALIEN, PRAYER, MOUNTAIN, SATAN, DRAGON, DIAMOND, PLATINUM, GOLD, DEVIL, FENCE, VIDEO_GAME, MATH, ROBOT, HEART, ELECTRICITY, LIGHTNING, MEDUSA, POWER, LASER, NUKE, SKY, TANK, HELICOPTER
}
